name: insight
channels:
  - pytorch
  - nvidia
  - nvidia/label/cuda-11.7.0
  - conda-forge
  - huggingface
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.7
  - torchmetrics
  - torchinfo
  - wandb
  - scipy
  - ray-tune
  - optuna
  - cuda-nvcc
  - numpy
  - pandas
  - matplotlib
  - bokeh
  - seaborn
  - jupyter
  - jupyterlab
  - ipython
  - ipywidgets
  - wandb
  - datasets
  - tensorboard
  - pip:
      - selectivesearch
      - 'lightning[extra]'
      - gradient
      - 'black[jupyter]'
      - flake8
      - torch-tb-profiler
